// Override the vb in physica
#let vb(body) = $bold(upright(body))$
#let ii = sym.dotless.i
#let al = sym.angle.l
#let ar = sym.angle.r
#let cdot = sym.dot.c
#let to = sym.arrow.r
#let span = text("span")
#let img = text("Im")
#let ker = text("Ker")
#let tp = sym.times.circle
#let sendto = sym.arrow.r.bar
#let L1 = $cal(L)^1$
#let L2 = $cal(L)^2$
#let Lp = $cal(L)^p$
#let caniso = sym.tilde.equiv
#let conj(body) = $overline(body)$
#let inv(body) = $body^(-1)$
#let spinup = $arrow.t$
#let spindown = $arrow.b$
#let pm = $plus.minus$
#let mp = $minus.plus$
#let ft(body, out) = $cal(F)[body](out)$
#let invft(body, out) = $cal(F)^(-1)[body](out)$
#let op(body) = $hat(body)$
#let vecop(body) = $underline(hat(body))$
